[profile.default]

via_ir = true
solc = "0.8.17"
test = 'test/foundry'
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
cache_path  = 'cache_forge'

remappings = [
    'forge-std=lib/forge-std/src/',
    'contracts/=contracts/',
]

optimizer = true
optimizer_runs = 200
fuzz_runs = 7500

block_timestamp = 1738389600

gas_reports = ["*"]
